import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pro-icare.com/auth/login');
  await page.getByRole('textbox', { name: 'Votre mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Votre mot de passe' }).fill('BcIsX7V&ZRh7');
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).click();
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).fill('NEST');
  await page.getByRole('textbox', { name: 'Votre identifiant' }).click();
  await page.getByRole('textbox', { name: 'Votre identifiant' }).fill('hi-admin');
  await page.getByRole('button', { name: 'Connexion' }).click();
  await page.getByText('Menu').nth(3).click();
  await page.getByRole('link', { name: ' Patients' }).click();
  await page.goto('https://pro-icare.com/patient/patients');
  await page.getByRole('button', { name: ' Nouveau patient' }).click();
  await page.getByRole('textbox', { name: 'Numéro Dossier' }).click();
  await page.getByRole('textbox', { name: 'Numéro Dossier' }).fill('P');
  await page.getByText('Numéro Dossier Sexe * Choisir').click();
  await page.locator('select[name="sex"]').selectOption('1');
  await page.locator('#lastName').click();
  await page.locator('#lastName').fill('Z');
  await page.locator('#firstName').click();
  await page.locator('#firstName').fill('l');
  await page.locator('#collapseOne_create input[name="doB"]').fill('2026-03-17');
  await page.getByRole('textbox', { name: 'Email', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('sa@com');
  await page.getByRole('textbox', { name: 'Entrez le numéro' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Entrez le numéro' }).nth(1).fill('787878787');
  await page.locator('#phone1').getByRole('textbox', { name: 'Entrez le numéro' }).click();
  await page.locator('#phone1').getByRole('textbox', { name: 'Entrez le numéro' }).fill('778899009');
  await page.locator('#address').click();
  await page.locator('#address').fill('dakar');
  await page.locator('#street').click();
  await page.locator('#street').fill('rue 22');
  await page.locator('.ng-select-searchable.ng-select-clearable.ng-select.ng-select-single.ng-untouched.ng-pristine.ng-invalid > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'SAINT-LOUIS' }).click();
  await page.locator('#state > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'KOLDA' }).click();
  await page.locator('#country > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'SENEGAL' }).click();
  await page.locator('#nationality > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'BENINOIS(E)' }).click();
  await page.locator('#hiConfigId > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'Désactivé' }).click();
  await page.getByRole('button', { name: 'Enregistrer' }).click();
  await page.getByRole('button', { name: 'Confirmer' }).click();
});