import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pro-icare.com/auth/login');
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).click();
  await page.getByRole('textbox', { name: 'Votre mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Votre mot de passe' }).fill('BcIsX7V&ZRh7');
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).click();
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).fill('NEST');
  await page.getByRole('textbox', { name: 'Votre identifiant' }).click();
  await page.getByRole('textbox', { name: 'Votre identifiant' }).fill('hi-admin');
  await page.getByRole('button', { name: 'Connexion' }).click();
  await page.getByText('Menu').nth(3).click();
  await page.getByRole('link', { name: ' Patients' }).click();
  await page.goto('https://pro-icare.com/patient/patients');
  await page.getByText('+221 76 543 22 11/+221 76 787 87').click();
  await page.locator('#content-page').click();
  await page.getByRole('link', { name: 'Voir Détails Administratifs' }).click();
  await page.getByRole('tab', { name: ' Personne à contacter' }).click();
  await expect(page.getByRole('link', { name: 'Ajouter une personne à' })).toBeVisible();
  await page.getByRole('link', { name: 'Ajouter une personne à' }).click();
  await expect(page.getByText('Ajouter personne à contacter×')).toBeVisible();
  await page.locator('#ctfirstName').click();
  await page.locator('#ctfirstName').fill('TRAORE');
  await page.locator('#ctlastName').click();
  await page.locator('#ctlastName').fill('MARUIS');
  await page.getByRole('textbox', { name: 'Entrez le numéro' }).first().click();
  await page.getByRole('textbox', { name: 'Entrez le numéro' }).first().fill('787878787');
  await page.getByRole('textbox', { name: 'Entrez le numéro' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Entrez le numéro' }).nth(1).fill('778899889');
  await page.locator('#ctlinkType').selectOption('17');
  await page.locator('#ctsexe').selectOption('1');
  await page.locator('#ctdoB').fill('2026-04-09');
  await page.locator('#ctrue').click();
  await page.locator('#ctrue').fill('78X78');
  await page.locator('#ctaddress').click();
  await page.locator('#ctaddress').fill('dakar');
  await page.locator('#ctville').selectOption('71');
  await page.locator('#ctregion').selectOption('52');
  await page.locator('#ctpays').selectOption('109');
  await page.locator('#ctnationalite').selectOption('35');
  await page.getByRole('button', { name: 'Enregistrer' }).click();
  await expect(page.getByRole('button', { name: 'Action' })).toBeVisible();
});