import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
 await page.goto('https://pro-icare.com/auth/login');
  await page.getByRole('textbox', { name: 'Votre mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Votre mot de passe' }).fill('BcIsX7V&ZRh7');
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).click();
  await page.getByRole('textbox', { name: 'Votre HI CODE' }).fill('NEST');
  await page.getByRole('textbox', { name: 'Votre identifiant' }).click();
  await page.getByRole('textbox', { name: 'Votre identifiant' }).fill('hi-admin');
  await page.getByRole('button', { name: 'Connexion' }).click();
  await page.getByText('Menu').nth(3).click();
  await page.getByRole('link', { name: ' Patients' }).click();
  await page.goto('https://pro-icare.com/patient/patients');
  
  // Cliquer sur la première ligne (dashboard patient)
  const firstRow = page.locator('.table-striped tbody tr:first-child');
  await firstRow.click();
  await page.getByRole('link', { name: 'Voir Détails Administratifs' }).click();
  await page.getByRole('tab', { name: ' Prise en charge' }).click();
  await expect(page.getByRole('link', { name: 'Ajouter une prise en charge' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: '#' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Assureur' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Souscripteur' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Début validité' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Fin validité' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Numéro assuré' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Numéro carte' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Taux' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Plafond (FCFA)' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Actions' })).toBeVisible();
  await page.getByRole('link', { name: 'Ajouter une prise en charge' }).click();
  await expect(page.getByRole('heading', { name: 'Ajouter prise en charge' })).toBeVisible();
  await page.locator('#insurerId').getByRole('textbox').click();
  await page.getByRole('option', { name: 'AMSA ASSURANCE (ASSURANCE)' }).click();
  await page.locator('#startingDate').fill('2026-04-01');
  await page.locator('#endingDate').fill('2026-04-26');
  await page.locator('#insuranceNumber').click();
  await page.locator('#insuranceNumber').fill('A123');
  await page.locator('#cardNumber').click();
  await page.locator('#cardNumber').fill('B3456YU');
  await page.locator('#coverateRate').click();
  await page.locator('#coverateRate').fill('25');
  await page.locator('#paymentCap').click();
  await page.locator('#paymentCap').fill('70');
  await page.locator('.ng-touched > .modal-dialog > .modal-content > .modal-body > div:nth-child(3) > .col-md-12 > .ng-select-multiple > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'SALLE D\'ACCOUCHEMENT' }).click();
  await page.locator('.ng-select-multiple.ng-select-searchable.ng-select-clearable.ng-select.ng-valid.ng-select-focused > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'CHAMBRE CATÉGORIE 2' }).click();
  await page.locator('.ng-touched > .modal-dialog > .modal-content > .modal-body > div:nth-child(4) > div > .ng-select-multiple > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'CHAMBRE CATÉGORIE' }).click();
  await page.locator('.ng-select-multiple.ng-select-searchable.ng-select-clearable.ng-select.ng-valid.ng-select-focused > .ng-select-container > .ng-value-container > .ng-input > input').click();
  await page.getByRole('option', { name: 'PHARMACIE' }).click();
  await page.locator('[id="1-HOSPITALISATIONROOMT"]').click();
  await page.locator('[id="1-HOSPITALISATIONROOMT"]').fill('10');
  await page.locator('[id="1-HOSPITALISATIONROOMM"]').click();
  await page.locator('[id="1-HOSPITALISATIONROOMM"]').fill('4000');
  await page.locator('[id="1-PHARMACIET"]').click();
  await page.locator('[id="1-PHARMACIET"]').fill('15');
  await page.locator('[id="1-PHARMACIEM"]').click();
  await page.locator('[id="1-PHARMACIEM"]').fill('2000');
  await expect(page.getByRole('button', { name: 'Fermer' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Enregistrer' })).toBeVisible();
  await page.getByRole('button', { name: 'Enregistrer' }).click();
 // await page.getByText('La date de fin doit être supé').click();
//  await page.locator('#endingDate').fill('2026-04-26');
  await page.getByRole('button', { name: 'Enregistrer' }).click();
});